apiVersion: apps/v1
kind: Deployment

metadata:
    name: go-server
    namespace: go-mongo
    labels:
        app: go-server

spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-server
    template:
        metadata:
            labels:
                app: go-server
        spec:
            containers:
                - name: go-server
                  image: tushartyke/go-mongo-server:latest
                  ports:
                      - containerPort: 8080
                  env:
                      - name: DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: mongodb-configmap
                                key: db_host
                      - name: DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: mongodb-configmap
                                key: db_port
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: db_username
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: db_password
                      - name: DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: db_name
                      - name: EMAIL
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: email

---
apiVersion: v1
kind: Service

metadata:
    name: go-server-service
    namespace: go-mongo

spec:
    # type: NodePort
    selector:
        app: go-server
    ports:
        - protocol: TCP
          port: 8080
        
          targetPort: 8080
        #   nodePort: 30000
