apiVersion: apps/v1
kind: Deployment

metadata:
    name: mongodb-deployment
    namespace: go-mongo
    labels:
        app: mongodb

spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            containers:
                - name: mongodb
                  image: mongo
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: db_username
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: db_password
                      - name: MONGO_INITDB_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: db_name

---
apiVersion: v1
kind: Service

metadata:
    name: mongodb-service
    namespace: go-mongo

spec:
    selector:
        app: mongodb
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
